CSRF_ENABLED = True
SECRET_KEY = 'niubo43!2dywlluybo875@13guessth*(7is'
LOCALDATABASE = 'shop_db'
HQDATABASE = 'temp_hq'
DEBUG = True
LOCALUSERNAME= 'CG3002Managers'
HQUSERNAME= 'sadm'
LOCALPASSWORD = 'group007'
HQPASSWORD = 'a+baby'
